//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace wx_site_micc.OAuthTwoService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OAuthTwoService.OAuthTwoServiceSoap")]
    public interface OAuthTwoServiceSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 agentid 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OAuthTwo", ReplyAction="*")]
        wx_site_micc.OAuthTwoService.OAuthTwoResponse OAuthTwo(wx_site_micc.OAuthTwoService.OAuthTwoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OAuthTwo", ReplyAction="*")]
        System.Threading.Tasks.Task<wx_site_micc.OAuthTwoService.OAuthTwoResponse> OAuthTwoAsync(wx_site_micc.OAuthTwoService.OAuthTwoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OAuthTwoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OAuthTwo", Namespace="http://tempuri.org/", Order=0)]
        public wx_site_micc.OAuthTwoService.OAuthTwoRequestBody Body;
        
        public OAuthTwoRequest() {
        }
        
        public OAuthTwoRequest(wx_site_micc.OAuthTwoService.OAuthTwoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class OAuthTwoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string agentid;
        
        public OAuthTwoRequestBody() {
        }
        
        public OAuthTwoRequestBody(string agentid) {
            this.agentid = agentid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OAuthTwoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OAuthTwoResponse", Namespace="http://tempuri.org/", Order=0)]
        public wx_site_micc.OAuthTwoService.OAuthTwoResponseBody Body;
        
        public OAuthTwoResponse() {
        }
        
        public OAuthTwoResponse(wx_site_micc.OAuthTwoService.OAuthTwoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class OAuthTwoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string OAuthTwoResult;
        
        public OAuthTwoResponseBody() {
        }
        
        public OAuthTwoResponseBody(string OAuthTwoResult) {
            this.OAuthTwoResult = OAuthTwoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface OAuthTwoServiceSoapChannel : wx_site_micc.OAuthTwoService.OAuthTwoServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OAuthTwoServiceSoapClient : System.ServiceModel.ClientBase<wx_site_micc.OAuthTwoService.OAuthTwoServiceSoap>, wx_site_micc.OAuthTwoService.OAuthTwoServiceSoap {
        
        public OAuthTwoServiceSoapClient() {
        }
        
        public OAuthTwoServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OAuthTwoServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OAuthTwoServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OAuthTwoServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        wx_site_micc.OAuthTwoService.OAuthTwoResponse wx_site_micc.OAuthTwoService.OAuthTwoServiceSoap.OAuthTwo(wx_site_micc.OAuthTwoService.OAuthTwoRequest request) {
            return base.Channel.OAuthTwo(request);
        }
        
        public string OAuthTwo(string agentid) {
            wx_site_micc.OAuthTwoService.OAuthTwoRequest inValue = new wx_site_micc.OAuthTwoService.OAuthTwoRequest();
            inValue.Body = new wx_site_micc.OAuthTwoService.OAuthTwoRequestBody();
            inValue.Body.agentid = agentid;
            wx_site_micc.OAuthTwoService.OAuthTwoResponse retVal = ((wx_site_micc.OAuthTwoService.OAuthTwoServiceSoap)(this)).OAuthTwo(inValue);
            return retVal.Body.OAuthTwoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wx_site_micc.OAuthTwoService.OAuthTwoResponse> wx_site_micc.OAuthTwoService.OAuthTwoServiceSoap.OAuthTwoAsync(wx_site_micc.OAuthTwoService.OAuthTwoRequest request) {
            return base.Channel.OAuthTwoAsync(request);
        }
        
        public System.Threading.Tasks.Task<wx_site_micc.OAuthTwoService.OAuthTwoResponse> OAuthTwoAsync(string agentid) {
            wx_site_micc.OAuthTwoService.OAuthTwoRequest inValue = new wx_site_micc.OAuthTwoService.OAuthTwoRequest();
            inValue.Body = new wx_site_micc.OAuthTwoService.OAuthTwoRequestBody();
            inValue.Body.agentid = agentid;
            return ((wx_site_micc.OAuthTwoService.OAuthTwoServiceSoap)(this)).OAuthTwoAsync(inValue);
        }
    }
}
