//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace wx_site_micc.GetTokenService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GetTokenService.GetTokenServiceSoap")]
    public interface GetTokenServiceSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 Agentid 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAccessToken", ReplyAction="*")]
        wx_site_micc.GetTokenService.GetAccessTokenResponse GetAccessToken(wx_site_micc.GetTokenService.GetAccessTokenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAccessToken", ReplyAction="*")]
        System.Threading.Tasks.Task<wx_site_micc.GetTokenService.GetAccessTokenResponse> GetAccessTokenAsync(wx_site_micc.GetTokenService.GetAccessTokenRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAccessTokenRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAccessToken", Namespace="http://tempuri.org/", Order=0)]
        public wx_site_micc.GetTokenService.GetAccessTokenRequestBody Body;
        
        public GetAccessTokenRequest() {
        }
        
        public GetAccessTokenRequest(wx_site_micc.GetTokenService.GetAccessTokenRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAccessTokenRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Agentid;
        
        public GetAccessTokenRequestBody() {
        }
        
        public GetAccessTokenRequestBody(string Agentid) {
            this.Agentid = Agentid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAccessTokenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAccessTokenResponse", Namespace="http://tempuri.org/", Order=0)]
        public wx_site_micc.GetTokenService.GetAccessTokenResponseBody Body;
        
        public GetAccessTokenResponse() {
        }
        
        public GetAccessTokenResponse(wx_site_micc.GetTokenService.GetAccessTokenResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAccessTokenResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetAccessTokenResult;
        
        public GetAccessTokenResponseBody() {
        }
        
        public GetAccessTokenResponseBody(string GetAccessTokenResult) {
            this.GetAccessTokenResult = GetAccessTokenResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GetTokenServiceSoapChannel : wx_site_micc.GetTokenService.GetTokenServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetTokenServiceSoapClient : System.ServiceModel.ClientBase<wx_site_micc.GetTokenService.GetTokenServiceSoap>, wx_site_micc.GetTokenService.GetTokenServiceSoap {
        
        public GetTokenServiceSoapClient() {
        }
        
        public GetTokenServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GetTokenServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetTokenServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetTokenServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        wx_site_micc.GetTokenService.GetAccessTokenResponse wx_site_micc.GetTokenService.GetTokenServiceSoap.GetAccessToken(wx_site_micc.GetTokenService.GetAccessTokenRequest request) {
            return base.Channel.GetAccessToken(request);
        }
        
        public string GetAccessToken(string Agentid) {
            wx_site_micc.GetTokenService.GetAccessTokenRequest inValue = new wx_site_micc.GetTokenService.GetAccessTokenRequest();
            inValue.Body = new wx_site_micc.GetTokenService.GetAccessTokenRequestBody();
            inValue.Body.Agentid = Agentid;
            wx_site_micc.GetTokenService.GetAccessTokenResponse retVal = ((wx_site_micc.GetTokenService.GetTokenServiceSoap)(this)).GetAccessToken(inValue);
            return retVal.Body.GetAccessTokenResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wx_site_micc.GetTokenService.GetAccessTokenResponse> wx_site_micc.GetTokenService.GetTokenServiceSoap.GetAccessTokenAsync(wx_site_micc.GetTokenService.GetAccessTokenRequest request) {
            return base.Channel.GetAccessTokenAsync(request);
        }
        
        public System.Threading.Tasks.Task<wx_site_micc.GetTokenService.GetAccessTokenResponse> GetAccessTokenAsync(string Agentid) {
            wx_site_micc.GetTokenService.GetAccessTokenRequest inValue = new wx_site_micc.GetTokenService.GetAccessTokenRequest();
            inValue.Body = new wx_site_micc.GetTokenService.GetAccessTokenRequestBody();
            inValue.Body.Agentid = Agentid;
            return ((wx_site_micc.GetTokenService.GetTokenServiceSoap)(this)).GetAccessTokenAsync(inValue);
        }
    }
}
