//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace wx_site_micc.SendMessageService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Error", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Error : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int errcodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string errmsgField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int errcode {
            get {
                return this.errcodeField;
            }
            set {
                if ((this.errcodeField.Equals(value) != true)) {
                    this.errcodeField = value;
                    this.RaisePropertyChanged("errcode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string errmsg {
            get {
                return this.errmsgField;
            }
            set {
                if ((object.ReferenceEquals(this.errmsgField, value) != true)) {
                    this.errmsgField = value;
                    this.RaisePropertyChanged("errmsg");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SendMessageService.SendMessageServiceSoap")]
    public interface SendMessageServiceSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 id 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QingJiaPushMessage", ReplyAction="*")]
        wx_site_micc.SendMessageService.QingJiaPushMessageResponse QingJiaPushMessage(wx_site_micc.SendMessageService.QingJiaPushMessageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QingJiaPushMessage", ReplyAction="*")]
        System.Threading.Tasks.Task<wx_site_micc.SendMessageService.QingJiaPushMessageResponse> QingJiaPushMessageAsync(wx_site_micc.SendMessageService.QingJiaPushMessageRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 id 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FangKePushMessage", ReplyAction="*")]
        wx_site_micc.SendMessageService.FangKePushMessageResponse FangKePushMessage(wx_site_micc.SendMessageService.FangKePushMessageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FangKePushMessage", ReplyAction="*")]
        System.Threading.Tasks.Task<wx_site_micc.SendMessageService.FangKePushMessageResponse> FangKePushMessageAsync(wx_site_micc.SendMessageService.FangKePushMessageRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QingJiaPushMessageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="QingJiaPushMessage", Namespace="http://tempuri.org/", Order=0)]
        public wx_site_micc.SendMessageService.QingJiaPushMessageRequestBody Body;
        
        public QingJiaPushMessageRequest() {
        }
        
        public QingJiaPushMessageRequest(wx_site_micc.SendMessageService.QingJiaPushMessageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class QingJiaPushMessageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string agentid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string send_class;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string send_type;
        
        public QingJiaPushMessageRequestBody() {
        }
        
        public QingJiaPushMessageRequestBody(string id, string agentid, string send_class, string send_type) {
            this.id = id;
            this.agentid = agentid;
            this.send_class = send_class;
            this.send_type = send_type;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QingJiaPushMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="QingJiaPushMessageResponse", Namespace="http://tempuri.org/", Order=0)]
        public wx_site_micc.SendMessageService.QingJiaPushMessageResponseBody Body;
        
        public QingJiaPushMessageResponse() {
        }
        
        public QingJiaPushMessageResponse(wx_site_micc.SendMessageService.QingJiaPushMessageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class QingJiaPushMessageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public wx_site_micc.SendMessageService.Error QingJiaPushMessageResult;
        
        public QingJiaPushMessageResponseBody() {
        }
        
        public QingJiaPushMessageResponseBody(wx_site_micc.SendMessageService.Error QingJiaPushMessageResult) {
            this.QingJiaPushMessageResult = QingJiaPushMessageResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FangKePushMessageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FangKePushMessage", Namespace="http://tempuri.org/", Order=0)]
        public wx_site_micc.SendMessageService.FangKePushMessageRequestBody Body;
        
        public FangKePushMessageRequest() {
        }
        
        public FangKePushMessageRequest(wx_site_micc.SendMessageService.FangKePushMessageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FangKePushMessageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string agentid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string send_class;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string send_type;
        
        public FangKePushMessageRequestBody() {
        }
        
        public FangKePushMessageRequestBody(string id, string agentid, string send_class, string send_type) {
            this.id = id;
            this.agentid = agentid;
            this.send_class = send_class;
            this.send_type = send_type;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FangKePushMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FangKePushMessageResponse", Namespace="http://tempuri.org/", Order=0)]
        public wx_site_micc.SendMessageService.FangKePushMessageResponseBody Body;
        
        public FangKePushMessageResponse() {
        }
        
        public FangKePushMessageResponse(wx_site_micc.SendMessageService.FangKePushMessageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FangKePushMessageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public wx_site_micc.SendMessageService.Error FangKePushMessageResult;
        
        public FangKePushMessageResponseBody() {
        }
        
        public FangKePushMessageResponseBody(wx_site_micc.SendMessageService.Error FangKePushMessageResult) {
            this.FangKePushMessageResult = FangKePushMessageResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SendMessageServiceSoapChannel : wx_site_micc.SendMessageService.SendMessageServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SendMessageServiceSoapClient : System.ServiceModel.ClientBase<wx_site_micc.SendMessageService.SendMessageServiceSoap>, wx_site_micc.SendMessageService.SendMessageServiceSoap {
        
        public SendMessageServiceSoapClient() {
        }
        
        public SendMessageServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SendMessageServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SendMessageServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SendMessageServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        wx_site_micc.SendMessageService.QingJiaPushMessageResponse wx_site_micc.SendMessageService.SendMessageServiceSoap.QingJiaPushMessage(wx_site_micc.SendMessageService.QingJiaPushMessageRequest request) {
            return base.Channel.QingJiaPushMessage(request);
        }
        
        public wx_site_micc.SendMessageService.Error QingJiaPushMessage(string id, string agentid, string send_class, string send_type) {
            wx_site_micc.SendMessageService.QingJiaPushMessageRequest inValue = new wx_site_micc.SendMessageService.QingJiaPushMessageRequest();
            inValue.Body = new wx_site_micc.SendMessageService.QingJiaPushMessageRequestBody();
            inValue.Body.id = id;
            inValue.Body.agentid = agentid;
            inValue.Body.send_class = send_class;
            inValue.Body.send_type = send_type;
            wx_site_micc.SendMessageService.QingJiaPushMessageResponse retVal = ((wx_site_micc.SendMessageService.SendMessageServiceSoap)(this)).QingJiaPushMessage(inValue);
            return retVal.Body.QingJiaPushMessageResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wx_site_micc.SendMessageService.QingJiaPushMessageResponse> wx_site_micc.SendMessageService.SendMessageServiceSoap.QingJiaPushMessageAsync(wx_site_micc.SendMessageService.QingJiaPushMessageRequest request) {
            return base.Channel.QingJiaPushMessageAsync(request);
        }
        
        public System.Threading.Tasks.Task<wx_site_micc.SendMessageService.QingJiaPushMessageResponse> QingJiaPushMessageAsync(string id, string agentid, string send_class, string send_type) {
            wx_site_micc.SendMessageService.QingJiaPushMessageRequest inValue = new wx_site_micc.SendMessageService.QingJiaPushMessageRequest();
            inValue.Body = new wx_site_micc.SendMessageService.QingJiaPushMessageRequestBody();
            inValue.Body.id = id;
            inValue.Body.agentid = agentid;
            inValue.Body.send_class = send_class;
            inValue.Body.send_type = send_type;
            return ((wx_site_micc.SendMessageService.SendMessageServiceSoap)(this)).QingJiaPushMessageAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        wx_site_micc.SendMessageService.FangKePushMessageResponse wx_site_micc.SendMessageService.SendMessageServiceSoap.FangKePushMessage(wx_site_micc.SendMessageService.FangKePushMessageRequest request) {
            return base.Channel.FangKePushMessage(request);
        }
        
        public wx_site_micc.SendMessageService.Error FangKePushMessage(string id, string agentid, string send_class, string send_type) {
            wx_site_micc.SendMessageService.FangKePushMessageRequest inValue = new wx_site_micc.SendMessageService.FangKePushMessageRequest();
            inValue.Body = new wx_site_micc.SendMessageService.FangKePushMessageRequestBody();
            inValue.Body.id = id;
            inValue.Body.agentid = agentid;
            inValue.Body.send_class = send_class;
            inValue.Body.send_type = send_type;
            wx_site_micc.SendMessageService.FangKePushMessageResponse retVal = ((wx_site_micc.SendMessageService.SendMessageServiceSoap)(this)).FangKePushMessage(inValue);
            return retVal.Body.FangKePushMessageResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wx_site_micc.SendMessageService.FangKePushMessageResponse> wx_site_micc.SendMessageService.SendMessageServiceSoap.FangKePushMessageAsync(wx_site_micc.SendMessageService.FangKePushMessageRequest request) {
            return base.Channel.FangKePushMessageAsync(request);
        }
        
        public System.Threading.Tasks.Task<wx_site_micc.SendMessageService.FangKePushMessageResponse> FangKePushMessageAsync(string id, string agentid, string send_class, string send_type) {
            wx_site_micc.SendMessageService.FangKePushMessageRequest inValue = new wx_site_micc.SendMessageService.FangKePushMessageRequest();
            inValue.Body = new wx_site_micc.SendMessageService.FangKePushMessageRequestBody();
            inValue.Body.id = id;
            inValue.Body.agentid = agentid;
            inValue.Body.send_class = send_class;
            inValue.Body.send_type = send_type;
            return ((wx_site_micc.SendMessageService.SendMessageServiceSoap)(this)).FangKePushMessageAsync(inValue);
        }
    }
}
